server:
  port: 9000
spring:
  #当出现相同名字的类进行注册时，准许覆盖注册
  main:
    allow-bean-definition-overriding: true
  application:
    name: demoservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/panta?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka



