server:
  port: 9001
spring:
  application:
    name: service-main
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/panta?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*Mapper.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka
