server:
  port: 9002
spring:
  #当出现相同名字的类进行注册时，准许覆盖注册
  main:
    allow-bean-definition-overriding: true
  application:
    name: cloud-redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9099/eureka



